name: Daily News Bot

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # v3에서 v4로 업데이트 (경고 해결)

      - name: Set up Python
        uses: actions/setup-python@v5  # v4에서 v5로 업데이트 (경고 해결)
        with:
          python-version: '3.10'

      - name: Install Tools
        run: |
          pip install google-generativeai feedparser requests

      - name: Run Python Script
        env:
          SLACK_URL: ${{ secrets.SLACK_URL }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py
